# Load these packages

library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(magrittr)
library(party)
library(randomForest)
library(rattle)
library(RColorBrewer)
library(rpart)
library(rpart.plot)
library(shiny)
library(stats)